export const user = {
  USER_LOGIN: "USER_LOGIN",
  USER_REFERRAL_ID: "USER_REFERRAL_ID",
  USER_SIGNUP: "USER_SIGNUP",
  USER_RESEND_EMAIL: "USER_RESEND_EMAIL",
  USER_EMAIL_VARIFICATION: "USER_EMAIL_VARIFICATION",
  USER_FORGOT_PASSWORD_SEND_OTP: "USER_FORGOT_PASSWORD_SEND_OTP",
  USER_FORGOT_PASSWORD_VERIFY_OTP: "USER_FORGOT_PASSWORD_VERIFY_OTP",
  USER_CHANGE_PASSWORD: "USER_CHANGE_PASSWORD",
  USER_WALLET_DETAILS: "USER_WALLET_DETAILS",
  USER_ENABLE2FAGENERATEQR: "USER_ENABLE2FAGENERATEQR",
  USER_ENABLE2FA: "USER_ENABLE2FA",
  USER_DISABLE2FA: "USER_DISABLE2FA",
  USER_VALIDATE2FA: "USER_VALIDATE2FA",
};

export const walletGetApi = {
  WALLET_PAYMODE_LIST: "WALLET_PAYMODE_LIST",
  WALLET_PAYMODE_ID_ADDRESS: "WALLET_PAYMODE_ID_ADRESS",
  WALLET_ADD_FUND: "WALLET_ADD_FUND",
  WALLET_VARIFY_TRANSFER: "WALLET_VARIFY_TRANSFER",
  WALLET_FUND_TRANSFER: "WALLET_FUND_TRANSFER",
  WALLET_AUTO_DEPOSIT: "WALLET_AUTO_DEPOSIT",
  WALLET_GET_MDR: "WALLET_GET_MDR",
  WALLET_GET_USDT: "WALLET_GET_USDT",
};

export const widthdrawal = {
  WIDTHDRAWAL_OTP_SEND: "WIDTHDRAWAL_OTP_SEND",
  WIDTHDRAWAL_VARIFY_OTP: "WIDTHDRAWAL_VARIFY_OTP",
  WIDTHDRAWAL_CALCULATE_AMOUNT: "WIDTHDRAWAL_CALCULATE_AMOUNT",
  WIDTHDRAWAL_PROCESS_AMOUNT: "WIDTHDRAWAL_PROCESS_AMOUNT",
  WIDTHDRAWAL_MATURITY_AMOUNT: "WIDTHDRAWAL_MATURITY_AMOUNT",
  MDR_USDT_RETOP_AMOUNT: "MDR_USDT_RETOP_AMOUNT",
};

export const dashboard = {
  EVENTS_LIST: "EVENTS_LIST",
  BYPACKAGES: "BYPACKAGES",
  DASHBOARD_DETAILS: "DASHBOARD_DETAILS",
  DASHBOARD_DETAILS_FAILED: "DASHBOARD_DETAILS_FAILED",
  MY_STAKES_REPORTS: "MY_STAKES_REPORTS",
  BYPACKAGES_HISTORY: "BYPACKAGES_HISTORY",
  TEAM_SUMMARY_DETAILS: "TEAM_SUMMARY_DETAILS",
  TEAM_LEVEL_SUMMARY_REPORTS: "TEAM_LEVEL_SUMMARY_REPORTS",
  TEAM_LEVEL_WISE_LIST: "TEAM_LEVEL_WISE_LIST",
};

export const transactions = {
  DAILY_INCOMING_REPORTS: "DAILY_INCOMING_REPORTS",
  DIRECT_INCOME_REPORTS: "DIRECT_INCOME_REPORTS",
  INCOME_WALLET_REPORTS: "INCOME_WALLET_REPORTS",
  TOPUP_WALLET_REPORTS: "TOPUP_WALLET_REPORTS",
  NTCL_WALLET_REPORTS: "NTCL_WALLET_REPORTS",
  LEVEL_INCOME_REPORTS: "LEVEL_INCOME_REPORTS",
  MATURITY_WALLET_REPORTS: "MATURITY_WALLET_REPORTS",
  MATURITY_WIDTHRAWAL_HISTORY_REPORTS: "MATURITY_WIDTHRAWAL_HISTORY_REPORTS",
  INCOME_AND_WALLET_SUMMERY: "INCOME_AND_WALLET_SUMMERY",
  TOPUP_TRANSFER_FUND: "TOPUP_TRANSFER_FUND",
  AUTO_DEPOSIT_REPORT: "AUTO_DEPOSIT_REPORT",
  MANUALFUND_TOPUP_DEPOSIT: "MANUALFUND_TOPUP_DEPOSIT",
  USER_TRANSACTION_REPORTS: "USER_TRANSACTION_REPORTS",
  FUND_REQUEST_LIST: "FUND_REQUEST_LIST",
  LEBEL_DETAILS_REPORT: "LEBEL_DETAILS_REPORT",
};

export const profile = {
  COUNTRY_LISTS: "COUNTRY_LISTS",
  USER_PROFILE_DETAILS: "USER_PROFILE_DETAILS",
  UPDATE_PROFILE_DETAILS: "UPDATE_PROFILE_DETAILS",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
};

export const setting = {
  ID_PROF_DOC_LISTS: "ID_PROF_DOC_LISTS",
  ADDRESS_PROF_DOC_LISTS: "ADDRESS_PROF_DOC_LISTS",
  UPDATE_KYC_DETAILS: "UPDATE_KYC_DETAILS",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
};

export const support = {
  NEW_TICKET: "NEW_TICKET",
  TICKET_CATEGORY_LIST : "TICKET_CATEGORY_LIST",
  TICKET_LIST : "TICKET_LIST",
  TICKET_DETAILS : "TICKET_DETAILS",
  CHAT_DETAILS : "CHAT_DETAILS",
  TICKET_REPLY : "TICKET_REPLY",
};


export const reward = {
  REWARDS_STATUS: "REWARDS_STATUS",
  REWARDS_TRACKING_REPORT: "REWARDS_TRACKING_REPORT",
};

